### ISSUE TITLE
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

### ISSUE THREAD

**Issue by luandro** [sonnylazuardi/ziliun-react-native#1]
Get this error when running `react-native run-android` on a fresh clone.

**Comment by sonnylazuardi** [comment]
@luandro what OS do you use?

**Comment by luandro** [comment]
OS X Yosmite

**Comment by kishanj918** [comment]
Facing the same issue.

**Comment by pewh** [comment]
I have same issue on OS X Mavericks too but this solution is work for me.

```
cd android
gradle wrapper
./gradlew installDebug
cd ..
react-native run-android
```

**Comment by BbosaH** [comment]
I get same error on same clone using windows 10

**Comment by akhileshsinha** [comment]
**react-native upgrade**  might fix this issue as it did in my case.
