### ISSUE TITLE
Generate data dari WP nya

### ISSUE THREAD

**Issue by aligos** [sonnylazuardi/ziliun-react-native#3]
Mas generate data dari WordPressnya pakai apa ?

**Comment by sonnylazuardi** [comment]
@aligos data wordpressnya sebenernya masih di crawl manual utk yang otomatis bisa pake https://wordpress.org/plugins/json-api/

**Comment by aligos** [comment]
crawl yang manual Mas pake node ?

**Comment by sonnylazuardi** [comment]
@aligos iya pake https://github.com/cheeriojs/cheerio
